name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Request to Streamlit App
        run: |
          curl --retry 5 --retry-delay 10 \
               --fail \
               https://testcasegen.streamlit.app/